### ISSUE TITLE
CI does no prevent from merge

### ISSUE THREAD

**Issue by deeplearningrobotics** [ApexAI/performance_test#37]
Even if CI fails it is still possible to merge a PR.

**Comment by dejanpan** [comment]
@deeplearningrobotics I've discussed with JP, basically what happened in https://github.com/ApexAI/performance_test/pull/25 is that the branch `multi_instance_experiment_script` was created before https://github.com/ApexAI/performance_test/pull/31 was introduced. 

And since we are here using `merge` instead of `rebase` strategy the CI did not get tiggered.

In addition I have now set up `master` branch protection which requires a) PR approval and b) checks (CI) to pass before one can merge.

See for instance this PR: https://github.com/ApexAI/performance_test/pull/38.

With this we can close the issue.
